Classes/Driver/AmazonS3Driver.php, Classes/Driver/Cache.php, composer.json, ext_localconf.php
This patch implements a full result cache on the `resolveFolderEntries` action. The result of this action is used to get a count of items and check if a folder contains subfolders (access to it is frequent).
Compared to uploading actual new files or creating the folders users like to read fast. This is what this patch aims to do. Directory listings are pretty static, and as soon a file is added the cache for that particular folder is flushed.
Targeted flushing is implemented in an attempt to prevent constant flushing and rebuilding of the whole file set if different users choose to update all their folders. By default the `File` backend is used since it supports TTL and tagging, but when used in a production setup you should consider `Redis` or some other alternative that doesn't hurt the …
=> Improve speed of browsing in filelist

Classes/Driver/AmazonS3Driver.php
It is useful to exclude some folders from TYPO3
even if present in S3
=> [FEATURE] Make it possible to exclude folders

Classes/Driver/AmazonS3Driver.php, Classes/Driver/Cache.php, ext_localconf.php
Calling cache->has has significant overhead, with no real benefit.
Instead we can just fetch the cache entry and if it does not
exist, proceed with generating the payload.
=> Improve performance of cache entry fetching

Classes/Driver/AmazonS3Driver.php, Classes/Driver/CachedDirectoryIterator.php
When iterating over files in S3 storage most time is spent
for I/O wait (the web requests to Amazon).
To improve performance reading the content of a directory should only
happen once and then be cached.
Instead of building multiple cache entries for one directory
(one with files, one with folders and one with both),
we fetch store only one entry with files and folders,
and filter the result requested from TYPO3 API.
By doing so, searching from root, will warmup the complete
cache, so that other storage listings will already be cached.
Now the caching logic is moved to a new CachedDirectoryIterator,
so we can remove the cache handling from the driver.
=> [BUGFIX] Improve caching of files and folders

Classes/Driver/AmazonS3Driver.php, Classes/Driver/CachedDirectoryIterator.php
We move the check which type of entries should be returned out of the iterator
into the driver, so that the iterator correctly finds children (directories)
Fixes: #21
=> [BUGFIX] Correctly recurse directories even when only files are requested

Classes/Driver/AmazonS3Driver.php
Changed the way of sorting in the backend, sorts with the identifier as keys and returns the array with array_keys so the identifier is the value again.
=> Fixed sorting issue in backend

Classes/CacheControl/RemoteObjectUpdater.php, Classes/Utility/RemoteObjectUtility.php, ext_localconf.php
If a new file is added or the metadata indexer is triggered update the metadata of the remote S3 object. This allows you to set cache control directives like `max-age` for specific file types.
Processed files are updated by monitoring the resource storage, since the filenames contain some kind of identifier the `max-age` in the dummy configuration is set to one week.
=> [FEATURE] - Update remote Cache-Control directives.

Classes/Driver/AmazonS3Driver.php
AmazonS3Driver->getFilesInFolder() accepted param for `$filenameFilterCallbacks`but it was never used. Use the same filtering method as the LocalDriver uses.
=> [FEATURE] Add file filtering similar to localDriver

Classes/Driver/AmazonS3Driver.php
LocalDriver uses readwhile so let's use it here as well. It directly output the contents of the file to the output buffer without reading file into memory, allowing download of much much bigger files.
=> [BUGFIX] fix memory issue when downloading large files

Classes/MetaData/RecordMonitor.php
Moved the DRIVER_KEY check to a different condition, so it's possible to upload non-image file to S3
=> Moved the DRIVER_KEY check to a different condition

Classes/CacheControl/RemoteObjectUpdater.php
Hi @arnoschoon 
We recently updated `fal_s3` from `v1.4.*` to `v1.8.*`, since the upgrade we are encountering issues with files that contain special characters such as umlauts `ä`, `ö` and `ü`. The following error is shown:
```
Error executing "CopyObject" on "https://some-portal-static.s3.eu-central-1.amazonaws.com/Webcontent/example.ch/fileadmin/_processed_/a/a/csm_Test_P%25C3%25A4ffgen_b45ad87de9.png"; 
AWS HTTP error: Client error: `PUT https://some-portal-static.s3.eu-central-1.amazonaws.com/Webcontent/example.ch/fileadmin/_processed_/a/a/csm_Test_P%25C3%25A4ffgen_b45ad87de9.png` resulted in a `404 Not Found` response: 
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>Webcontent/example.ch/fileadmin/_p (truncated...) 
NoSuchKey (client): The …
```
=> Fixes keys with special characters not working

Classes/Driver/AmazonS3Driver.php, composer.json, ext_emconf.php
Fixed issue with fileExistsCache when a file was already checked before the creation of the actual file during runtime. fileExistsCache array key is unset after creation.
=> CMS 9 compatibility + bugfix for fileExistsCache

Classes/Driver/Cache.php
If there isn't a CacheManager registered yet, you need to set the
cacheConfiguration, otherwise the cache identifier won't be found.
By setting the configuration in this method, you are sure the configuration
is loaded, before getting the cache frontend of tx_fal_s3
=> [BUGFIX] Set cacheConfiguration after initiating new CacheManager

Classes/Driver/AmazonS3Driver.php
Currently there is a bug when the number of folders (e.g. 42) exceeds the limit of items shown (e.g. 40) in the file list. TYPO3 handles this special case with setting `$filesFrom=false;` and `$filesNum=false;`. (Better would probably be `$filesFrom=0;` and `$filesNum=0;`, but that's just how it is.)
See https://github.com/TYPO3/TYPO3.CMS/blob/2c8df8f59068e1861606ff1dc0f35c693ffd5393/typo3/sysext/filelist/Classes/FileList.php#L303-L306
The way `getFilesInFolder` is implemented at the moment results in showing all files for this special case, because we pass `null` as length to `array_slice`:
https://github.com/MaxServ/t3ext-fal_s3/blob/b3a0fc62b24ef514d0cd03eee82b5027fb9e9126/Classes/Driver/AmazonS3Driver.php#L928-L932
This pull request fixes the issue and makes the `fal_s3` driver behave …
=> [Bugfix] File list showing all files when number of folder exceeds number of items (iLimit / filesPerPage) shown

Classes/CacheControl/RemoteObjectUpdater.php
The variable `$cacheControl` is initialised with `null`:
https://github.com/MaxServ/t3ext-fal_s3/blob/fe076675088f2ab0ed4bae80e44474a22eb1ca92/Classes/CacheControl/RemoteObjectUpdater.php#L110
But it will always be changed to a string after one of the following methods has been called, because `implode(',', [])` returns an empty string instead of `null`.
https://github.com/MaxServ/t3ext-fal_s3/blob/fe076675088f2ab0ed4bae80e44474a22eb1ca92/Classes/CacheControl/RemoteObjectUpdater.php#L138-L145
Thus the following condition is not working to check whether metadata should be updated or not.
https://github.com/MaxServ/t3ext-fal_s3/blob/fe076675088f2ab0ed4bae80e44474a22eb1ca92/Classes/CacheControl/RemoteObjectUpdater.php#L147-L151
I changed the condition to `!empty($cacheControl)`, which …
=> [Bugfix] Metadata updated even if no cache control has been set

Classes/CacheControl/RemoteObjectUpdater.php
This patch adds a check if the local cache-control directive isn't already set remotely so we can skip `copyObject`. This should fix the race condition discussed in https://github.com/MaxServ/t3ext-fal_s3/issues/49
=> [BUGFIX] - Only update storage metadata in case of changes

Classes/Driver/AmazonS3Driver.php
Remove rtrim in folderExists method to prevent files with the same name as folder to cause problems with storageMounts for users.
=> Remove rtrim in folder exists pathname

.gitattributes
This will make the output when loading it through composer (and zip) for production slimmer and make the required bandwidth to download your package smaller
=> add a gitattributes

Classes/Driver/AmazonS3Driver.php
The setting `folderCreateMask` should be read from `$GLOBALS['TYPO3_CONF_VARS']['SYS']['folderCreateMask']`:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.6/Important-36166-MoveAccessRightParametersFromBEToSYSConfiguration.html
I implemented it the same way TYPO3 does it in `GeneralUtility`:
https://github.com/TYPO3/TYPO3.CMS/blob/630f7c168f64d7fa045ac7f76af01f6381f1997b/typo3/sysext/core/Classes/Utility/GeneralUtility.php#L1989
=> [Bugfix] Fixes folderCreateMask read from old configuration path

CHANGELOG.md, Classes/Driver/AmazonS3Driver.php
Fix mkdir not working with octdec value, let S3 determine permissions (ACL) inside the S3 StreamWrapper for the mkdir method.
Before, in versions lower than 1.10, the mkdir method was passing `null` to the mkdir method by accident (TYPO3 core changed the configuration path) and during that time, the Amazon S3 StreamWrapper was determing the permissions (and corresponding ACL) by itself. In version 1.10 and higher, the path to the TYPO3 configuration value has been fixed and wrapped the value in octdec which made the StreamWrapper incorrectly determine the correct permissions and correcsponding ACL.
With this change, the mkdir method will receive `0`. This prevents strict type issues, because mkdir expects an integer as permissions argument. `null` and `0` will both let the StreamWrapper …
=> [TASK] Fix mkdir not working reliable with S3 ACL calculation

Classes/Driver/AmazonS3Driver.php, Classes/Service/Extraction/ExifToolMetadataExtraction.php, Classes/Service/Extraction/ImageDimensionsExtraction.php, Classes/Service/Extraction/PdfinfoMetadataExtraction.php, Classes/Service/Extraction/PhpMetadataExtraction.php, Classes/Service/Extraction/TikaLanguageDetector.php, Classes/Service/Extraction/TikaMetadataExtraction.php, composer.json, ext_emconf.php, ext_localconf.php
With this adjustment, an optional dependency has been added for the [causal/extractor](https://github.com/xperseguers/t3ext-extractor) extension to enrich the metadata that is being added to the TYPO3 metadata tables.
This way, additional data other than image dimensions and the default metadata can be extracted too while uploading or replacing files in the file admin.
The extractor Extraction classes have been XClasses because the could not be extended by using the Extbase object container, and the possible drivers can not be configured manually from within the extensions configuration.
Besides the adjustment for the XClasses Extraction services, the already implemented extractor has been renamed and moved to the Service/Extraction namespace and has been renamed to …
=> Add suggestion for causal/extractor for extended metadata extraction

CHANGELOG.md, Classes/Driver/AmazonS3Driver.php
The `countFilesInFolder` and `countFoldersInFolder` methods in the driver class were heavy and had to be executed everytime someone opened a folder.
The file and folder counts are being used in the filelist module to show the number of subfiles and -folders.
Without using the caching mechanism in the count methods, the driver had to fetch all files folders from S3 of the S3 caches, and count the result. When using the cache, the count will only be calculated once and fetched from cache.
By setting the cache tags equal to the cache tag set by the `CachedDirectoryIterator` for a directory, whe count caches will be cleared when a file or folder is being added, changed or removed from within the filelist.
An edge-case where incorrect counts are being saved, could occur if files or folders are …
=> [FEATURE] Use caches for file and folder count methods in driver

Classes/Driver/AmazonS3Driver.php, Classes/Resource/Event/FlushCacheActionEvent.php
Class `FlushCacheActionEvent` tries to take care of undefined array key access, but due to operator precedence the coalesce operator does not prevent it. Adding brackets takes care of the issue.
=> [BUGFIX] Prevent undefined array key access
